# hello_world:
#   description: >-
#     As is tradition in software, let's start by saying 'Hello, World!'. Then, pick
#     one or two tasks that they should try to do next with AgentStack.
#   expected_output: >-
#     The sentence Hello, World! followed by two things the user should try to customize
#     their agent further.
#   agent: >-
#     alex
edit_blog_post:
  description: >-
    Help the user edit it for clarity, grammar, and style
    based on the file located at: {file_path}
  expected_output: >-
    A revised version of the blog post located at {file_path} in markdown format, while
    keeping any inline HTML.  Annotate the document with notes on what was changed
    and why.  Write it out to a file with a name of your choosing.
  agent: >-
    musings_editor
